import 'package:speakup/models/universal_tile_model.dart';

List<UniversalTile> alphabetTiles = [
  UniversalTile(emoji: "🅰", title: "A"),
  UniversalTile(emoji: "🅱", title: "B"),
  UniversalTile(emoji: "👌", title: "C"),
  UniversalTile(emoji: "🙏", title: "D"),
  UniversalTile(emoji: "🤗", title: "E"),
  UniversalTile(emoji: "👋", title: "F"),
  UniversalTile(emoji: "🤝", title: "G"),
  UniversalTile(emoji: "👍", title: "H"),
  UniversalTile(emoji: "🙅‍♂️", title: "I"),
  UniversalTile(emoji: "👌", title: "J"),
  UniversalTile(emoji: "🙏", title: "K"),
  UniversalTile(emoji: "🤗", title: "L"),
  UniversalTile(emoji: "😊", title: "M"),
  UniversalTile(emoji: "👋", title: "N"),
  UniversalTile(emoji: "🤝", title: "O"),
  UniversalTile(emoji: "👍", title: "P"),
  UniversalTile(emoji: "🙅‍♂️", title: "Q"),
  UniversalTile(emoji: "👌", title: "R"),
  UniversalTile(emoji: "🙏", title: "S"),
  UniversalTile(emoji: "🤗", title: "T"),
  UniversalTile(emoji: "😊", title: "U"),
  UniversalTile(emoji: "👋", title: "V"),
  UniversalTile(emoji: "🤝", title: "W"),
  UniversalTile(emoji: "🤝", title: "X"),
  UniversalTile(emoji: "🤝", title: "Y"),
  UniversalTile(emoji: "🤝", title: "Z"),
];
